### ISSUE TITLE
[craftedv2beta] Broken configuration guards (Tracking Issue)

### ISSUE THREAD

**Issue by jvdydev** [SystemCrafters/crafted-emacs#313]
Tracking issue for the broken guard issue in craftedv2beta.

Affected modules (contain `featurep`):
- [x] crafted-completion (PR #294)
- [x] crafted-defaults (PR #317)
- [x] crafted-evil (PR #319)
- [x] crafted-ide (PR #320)
- [x] crafted-lisp (PR #328)
- [x] crafted-org (PR #322)
- [x] crafted-osx (PR #343)
- [x] crafted-screencast (PR #304)
- [x] crafted-ui (PR #318)
- [x] crafted-writing (PR #329)

Since the guards don't work, there might be more bugs below, therefor it would be nice to deal with these on a module-by-module basis (as suggested by @sthesing).

The proposed fixed guard patterns we want to apply (see #294 for the discussion).

```emacs-lisp
;; (require 'vertico) is in the guard anyway, so we might as well use it as a guard?
(when (require 'vertico nil :noerror)
    ;; vertico conf here ...
    )

;; consult does not need a require for the config, so locate-library anyway
(when (locate-library 'consult)
    ;; consult conf here ...
    )

;; maybe (as needed)
(when (or (featurep 'vertico)
          (require 'vertico nil :noerrror))  ; whichever guard as appropriate
    ;; vertico conf here
    )
```

Quote from #294 by @jeffbowman regarding how to apply the pattern above:

```markdown
[I]f we need to require something anyway, lets use the require guard, 
otherwise lets consider using the `locate-library` guard. 
Mindfully, we can add `featurep` with `or` if that makes sense 
(although I expect there will be very few examples where that would be useful).
```

Further discussion and/or contributions welcome :smile:

**Comment by monora** [comment]
Could we provide a macro for the two use-cases? Perhaps like this:

```emacs-lisp
(defmacro crafted-when-package-installed-do (package use-require &rest body)
  `(when (if ,use-require
             (require ,package nil :noerror)
           (locate-library (symbol-name ,package)))
           ,@body))
```
Usage:
```emacs-lisp
(crafted-when-package-installed-do 'vertico t
  ;; vertico conf)

(crafted-when-package-installed-do 'consult nil
  ;; vertico conf)
```

Then we could easily find the usage of the pattern.

**Comment by jeffbowman** [comment]
Macros are indeed a great tool to use, this kind of situation might be a good fit even.  However, we have a stated goal (see the Goals section of the README on the `craftedv2beta` branch) of avoiding (mindfully) using macros to keep things simple(r).  A macro might obfuscate what is going on for someone new to the project and we would rather be more transparent (even if redundant) about the structure of the code and reasons behind it.  For this reason, we will probably not introduce macros - at least as much as possible.

**Comment by jvdydev** [comment]
I'm not sure if we have anyone with a macOS system to fix and test `crafted-osx`.

If there is someone who wants to tackle it, please make it known here, otherwise I'll see if I can fix it up and find a Mac to test on some time early next month.

**Comment by sthesing** [comment]
With #343, the last the tasks on the list is completed. Closed.
